CREATE DATABASE IF NOT EXISTS STUDENT_DB;

USE STUDENT_DB;

DROP TABLE IF EXISTS STUDENT;

CREATE TABLE STUDENT
(SSN STRING, FIRST_NAME STRING, LAST_NAME STRING, RACE STRING, AGE INT, STATE STRING)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ',';